const path = require('path');
const Consultation = require('../models/Consultation');
const logger = require('../utils/logger');

/**
 * Generate a PDF for a consultation using an HTML template.
 * Returns a Buffer of PDF bytes.
 * 
 * Uses puppeteer if available, falls back to a simple HTML response.
 */
const generateConsultationPdf = async (consultation) => {
  let puppeteer;
  try {
    puppeteer = require('puppeteer');
  } catch {
    logger.warn('Puppeteer not installed — PDF generation unavailable');
    throw new Error('PDF generation requires puppeteer. Run: npm install puppeteer');
  }

  const html = buildHtml(consultation);

  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
    });
    return pdfBuffer;
  } finally {
    await browser.close();
  }
};

const buildHtml = (consultation) => {
  const topQuestions = consultation.questions.filter((q) => q.isTop);
  const otherQuestions = consultation.questions.filter((q) => !q.isTop);

  // Group non-top questions by category
  const grouped = {};
  otherQuestions.forEach((q) => {
    if (!grouped[q.categoryName]) grouped[q.categoryName] = [];
    grouped[q.categoryName].push(q);
  });

  const groupedHtml = Object.entries(grouped)
    .map(
      ([cat, qs]) => `
      <div class="category">
        <h3>${cat}</h3>
        <ul>
          ${qs.map((q) => `<li>${q.text}</li>`).join('')}
        </ul>
      </div>
    `
    )
    .join('');

  const customHtml =
    consultation.customQuestions && consultation.customQuestions.length
      ? `<div class="category">
          <h3>My Custom Questions</h3>
          <ul>${consultation.customQuestions.map((q) => `<li>${q}</li>`).join('')}</ul>
        </div>`
      : '';

  const topHtml = topQuestions.length
    ? `<div class="top-section">
        <h2>⭐ My Top Priority Questions</h2>
        <ol>${topQuestions.map((q) => `<li><strong>${q.text}</strong></li>`).join('')}</ol>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>My Consultation Questions</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a2e; padding: 20px; }
    .header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 24px; color: #6366f1; }
    .header .meta { font-size: 13px; color: #666; margin-top: 6px; }
    .top-section { background: #faf5ff; border-left: 4px solid #8b5cf6; padding: 16px; margin-bottom: 24px; border-radius: 4px; }
    .top-section h2 { font-size: 16px; color: #6d28d9; margin-bottom: 10px; }
    .top-section ol { padding-left: 20px; }
    .top-section li { margin-bottom: 8px; font-size: 14px; }
    .category { margin-bottom: 20px; }
    .category h3 { font-size: 14px; color: #4f46e5; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; margin-bottom: 10px; }
    .category ul { list-style: disc; padding-left: 20px; }
    .category li { font-size: 13px; margin-bottom: 6px; line-height: 1.5; }
    .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 12px; font-size: 11px; color: #999; }
  </style>
</head>
<body>
  <div class="header">
    <h1>My Consultation Questions</h1>
    <div class="meta">
      <strong>Condition:</strong> ${consultation.diseaseName} &nbsp;|&nbsp;
      <strong>Stage:</strong> ${consultation.stage} &nbsp;|&nbsp;
      <strong>Date:</strong> ${new Date(consultation.createdAt).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
    </div>
  </div>

  ${topHtml}
  ${groupedHtml}
  ${customHtml}

  <div class="footer">Generated by QLP — Question List Preparation App &nbsp;|&nbsp; ${new Date().toISOString()}</div>
</body>
</html>`;
};

module.exports = { generateConsultationPdf };
